export type CourseEventName =
  | 'Course created'
  | 'Course creation failed – invalid title'
  | 'Course creation failed – invalid description'
  | 'Course creation failed – invalid cover'
  | 'Course creation failed – server error'
  | 'Chapter added'
  | 'Chapter add failed – empty title'
  | 'Chapter add failed – server error'
  | 'Lesson added'
  | 'Lesson add failed – empty title'
  | 'Lesson add failed – server error'
  | 'Theory page added'
  | 'Test page added'
  | 'Detailed answer page added'
  | 'Code page added'
  | 'Page add failed – empty title'
  | 'Theory page add failed – server error'
  | 'Theory page saved'
  | 'Theory page content (text) add failed – server error'
  | 'Theory page content (MD) add failed – server error'
  | 'Theory page content (VID) add failed – server error'
  | 'Test page saved'
  | 'Test page content saved failed – server error'
  | 'Code page saved'
  | 'Code page add failed – server error'
  | 'Detailed answer page saved'
  | 'Detailed answer page save failed – server error'
  | 'Version saved'
  | 'Version restored'
  | 'Version save failed – server error'
  | 'Collaborator added'
  | 'Collaborator add failed – user not found'
  | 'Collaborator add failed – user already added'
  | 'Collaborator add failed – server error'
  | 'Course published'
  | 'Course publication failed – requirements not met'
  | 'Course publication failed – server error'
  | 'Course archivation failed – server error'
  | 'Course delete failed – server error'
  | 'Tags added'
  | 'Tags add failed – server error'
  | 'Tags deleted'
  | 'Tags delete failed – server error'
  | 'Course preview failed – server error'
  | 'AI text enhancement success'
  | 'AI text enhancement failed'
  | 'AI service unavailable'
  | 'AI invalid response'
  | 'AI test generation success'
  | 'AI test generation failed'
  | 'AI test generation insufficient context'
  | 'AI code task generation success'
  | 'AI code task generation failed'
  | 'AI code task generation invalid parameters'
  | 'Quiz submitted'
  | 'Code submitted'
  | 'Detailed answer submitted'
  | 'AI explanation requested'
  | 'AI hint requested'
  | 'Learning & Progress Service connection error – ошибка пересчёта статистики'
  | 'User enrolled';

export function logCourseEvent(event: CourseEventName, payload?: unknown) {
  // Пока просто логируем в консоль. Дальше можно прокинуть в аналитику.
  // eslint-disable-next-line no-console
  console.log(`[course-event] ${event}`, payload ?? '');
}
